### ISSUE TITLE
Diffs with GAP stable-4.10 branch

### ISSUE THREAD

**Issue by alex-konovalov** [simpcomp-team/simpcomp#10]
Tests of SimpComp package in stable-4.10 branch of GAP fail in all three configurations: please see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.10-staging/jobs/438054217. It will be very useful to investigate and fix this, and make a new release within October in time for the planned GAP 4.10 release.

**Comment by simpcomp-team** [comment]
Ok, will look into this.

**Comment by simpcomp-team** [comment]
I was able to fix one thing which was responsible for most of the errors. -A option now does not produce any errors.

The assertion errors at lines 968 and 1201 (which first occurred in May) are still a mystery to me. They occur when "SimplifiedFpGroup" is called for a finitely presented group with one generator and one relation which is trivial (this group returns "true" on calling "IsTrivial", prints generators and relations, i.e., I do not see what is wrong with it). 

Running the relevant commands from the test file on their own but using the same gap configuration (-r option or "LoadAllPackages()") does not reproduce the error.

**Comment by simpcomp-team** [comment]
Another thing I noticed: we use the io package to save simplicial complexes in binary format. Saving them and then reading them in is not a problem (so I assume our code works, at least in some instances). 

But some binary files we produced with an older version of io (and which we still use in our complex library) now produce the error "Found a self-reference to an unknown object!". As soon as this happens something breaks severely and reading the files does not produce an error anymore but loaded data is corrupted.

Are you aware of similar problems with other packages?

**Comment by alex-konovalov** [comment]
Thanks. Tests run with assertion level 2 - please try `SetAssertionLevel( 2 );` before you run commands from the test file manually, and check if you will get an assertion error then.

Regarding IO, I suggest to submit an issue at https://github.com/gap-packages/io/.

**Comment by simpcomp-team** [comment]
Many thanks for clarifying.

I was now able to isolate the assertion error. Here is what goes wrong: at some point simpcomp calls `SimplifiedFpGroup` using a finitely presented group on one generator and one relation where the relation equals the generator (in other words, the group is a very simple presentation of the trivial group). This causes the assertion error. 

Below I reproduced the error without loading `simpcomp`.

    jspreer@smp-c8p3tz1:~/GAP/gap-repository$ ./bin/gap.sh -r
     ┌───────┐   GAP 4.10dev-1285-g44f1a0c of today
     │  GAP  │   https://www.gap-system.org
     └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv5
     Configuration:  gmp 6.1.0, GASMAN, readline
     Loading the library and packages ...
     Packages:   AClib 1.3, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2018.09.20, 
                 AutPGrp 1.10, Browse 1.8.8, Carat 2.2.2, CRISP 1.4.4, 
                 Cryst 4.1.17, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, 
                 FGA 1.4.0, GAPDoc 1.6.1, IO 4.5.4, IRREDSOL 1.4, LAGUNA 3.9.0, 
                 Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.1, RadiRoot 2.8, 
                 ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, 
                 TomLib 1.2.6, TransGrp 2.0.4, utils 0.58
     Try '??help' for help. See also '?copyright', '?cite' and '?authors'
    gap> SetAssertionLevel(2);
    gap> g:=FreeGroup("a");
    <free group on the generators [ a ]>
    gap> gens:=GeneratorsOfGroup(g);
    [ a ]
    gap> rels:=[gens[1]];
    [ a ]
    gap> G:=g/rels;
    <fp group on the generators [ a ]>
    gap> SimplifiedFpGroup(G);
    Error, Assertion failure in
      Assert( 2, ForAll( imgs, function ( x )
            return x in H;
        end ) ); at /home/jspreer/GAP/gap-repository/lib/ghom.gi:309 called from 
    GroupGeneralMappingByImagesNC( G, H, gens, imgs 
     ) at /home/jspreer/GAP/gap-repository/lib/ghom.gi:439 called from
    GroupHomomorphismByImagesNC( G, H, GeneratorsOfGroup( G ), 
     List( TzImagesOldGens( T ), function ( i )
            return MappedWord( i, GeneratorsOfPresentation( T ), 
               GeneratorsOfGroup( H ) );
        end ) ) at /home/jspreer/GAP/gap-repository/lib/tietze.gi:1214 called from
    <function "SimplifiedFpGroup">( <arguments> )
     called from read-eval loop at *stdin*:6
    you may 'return;'
    brk>

**Comment by alex-konovalov** [comment]
@simpcomp-team I can reproduce this with the latest clone of the stable-4.10 branch. Could you please report this in an issue at https://github.com/gap-system/gap/issues ?

**Comment by simpcomp-team** [comment]
Yes. Will do so.

**Comment by fingolfin** [comment]
As to the [issue with IO](https://github.com/gap-packages/io/issues/72), I believe this  is a bug on the simpcomp side, i.e., a corrupt data file. For details please refer to the IO issue.

**Comment by simpcomp-team** [comment]
Ok, my suggestion is then to try and recompile the simpcomp complex library. Will close the [issue with IO](https://github.com/gap-packages/io/issues/72) once this is running.

**Comment by fingolfin** [comment]
You could also try to get the data files from an old, known-good version of simpcomp. E.g. ftp://ftp.gap-system.org/pub/gap/gap45/tar.bz2/packages/simpcomp-1.5.4.tar.bz2

**Comment by fingolfin** [comment]
I think this was closed by accident, when you pushed that `gh-pages` branch -- this is essentially my fault, for having a polluted history in that repo. I'll take care of that now. My apologies for the annoyance.

**Comment by alex-konovalov** [comment]
So someone with appropriate rights please reopen this.

**Comment by simpcomp-team** [comment]
Just published a new release. With a pull from the stable-4.10 branch from today (20/10/2018) now only `gap -r` produces the assertion error.

The new version 2.1.9 now requires the special `simpcomp` option in `BuildPackages.sh` to be removed. I created a [pull request](https://github.com/gap-system/gap/pull/2935) for this edit, hope this is fine.

**Comment by alex-konovalov** [comment]
Thanks - I hope to see the new release being picked up smoothly on Monday then. I do not understand  `-r` command line option is relevant though. I expect that the assertion error will be gone after merging and backporting https://github.com/gap-system/gap/pull/2917

**Comment by alex-konovalov** [comment]
All diffs are gone - thanks: https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.10-staging/jobs/446654836
