### ISSUE TITLE
PackageWWWHome URL not usable

### ISSUE THREAD

**Issue by fingolfin** [simpcomp-team/simpcomp#11]
Right now, this is set in your `PackageInfo.g`:
```
PackageWWWHome := "http://raw.githubusercontent.com/simpcomp-team/simpcomp/master/web/",
```
However, in my web browser, going to that URL just results in a file being downloaded. Not a surprise, as GitHub serves all content with MIME type `text/plain`, *precisely* to prevent people from abusing it for hosting websites ;-).

You could use GitHubPages instead, or even https://github.com/gap-system/GitHubPagesForGAP

**Comment by simpcomp-team** [comment]
We actually already use github pages: [https://simpcomp-team.github.io/simpcomp/chap0.html](https://simpcomp-team.github.io/simpcomp/chap0.html). But for some reason we did not add it to `PackageInfo.g`.

I changed `PackageInfo.g` to

    PackageWWWHome := "https://simpcomp-team.github.io/simpcomp/chap0.html",
    README_URL := "http://raw.githubusercontent.com/simpcomp-team/simpcomp/master/web/README",
    PackageInfoURL := "http://raw.githubusercontent.com/simpcomp-team/simpcomp/master/web/PackageInfo.g",

Hope this is fine.

**Comment by fingolfin** [comment]
As long as you are aware that this setup implies that whenever you commit an update to your `PackageInfo.g` file, it will "immediately" be picked up by the GAP package distribution tools, which will then try to download the new version. So you have no time to e.g. validate a new release and/or run final tests on it.

So while you can do this, in general I recommend hosting a dedicated copy of the README and PackageInfo.g on the website. This is what [ReleaseTools](https://github.com/gap-system/ReleaseTools) and [GitHubPagesForGAP](https://github.com/gap-system/GitHubPagesForGAP) do by default.

**Comment by simpcomp-team** [comment]
Ok. So, what about this:

    PackageWWWHome := "https://simpcomp-team.github.io/simpcomp/chap0.html",
    README_URL := "https://simpcomp-team.github.io/simpcomp/README",
    PackageInfoURL := "https://simpcomp-team.github.io/simpcomp/PackageInfo.g",

These files are only updated when a new version is published.

**Comment by fingolfin** [comment]
That looks perfect, thanks :)

**Comment by alex-konovalov** [comment]
This looks better, although I do not really like using the manual as a poor man replacement for a package website ;-) Also, currently it is not displayed properly because apparently you did not copy css and js files - compare with e.g. how GAPDoc based manual looks at http://gap-packages.github.io/example/doc/chap0.html

**Comment by fingolfin** [comment]
Note again that all of these issues are automatically taken care of by [ReleaseTools](https://github.com/gap-system/ReleaseTools) and [GitHubPagesForGAP](https://github.com/gap-system/GitHubPagesForGAP) ;-)

**Comment by simpcomp-team** [comment]
OK, I'll look into GitHubPagesForGAP...

**Comment by simpcomp-team** [comment]
It's working now: [https://simpcomp-team.github.io/simpcomp/](https://simpcomp-team.github.io/simpcomp/)

`PackageInfo.g` will be looking like:

    PackageWWWHome := "https://simpcomp-team.github.io/simpcomp",
    README_URL := Concatenation( ~.PackageWWWHome, "README" ),
    PackageInfoURL := Concatenation( ~.PackageWWWHome, "PackageInfo.g" ),

**Comment by alex-konovalov** [comment]
Nice webpage:) The manual is still displayed incorrectly though.

When you will have a new release waiting to be picked up, I hope it will work for your case without updating the URL in https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList, since you still have control over http://raw.githubusercontent.com/simpcomp-team/simpcomp/master/web/PackageInfo.g and that will be exactly the one from the released version. I will then see that it has been picked up and update the URL myself.

**Comment by simpcomp-team** [comment]
Sorry, one more thing. I get an error: 

A file was included in `README.html` that is a symlink or does not exist in your `_includes` directory. 

Also, I follow the steps for updating the website but it does not update. In particular, [https://simpcomp-team.github.io/simpcomp/PackageInfo.g](https://simpcomp-team.github.io/simpcomp/PackageInfo.g) is still an old version.

Any idea what might have gone wrong?

**Comment by fingolfin** [comment]
I assume you get that error when you run `jekyll` to test build the site locally? And/or GitHub reports that error via email? In both cases, that means the site is not actually building, and hence won't be updated locally.

Anyway, the problem is in your `PackageInfo.g`:
```gap
PackageWWWHome := "https://simpcomp-team.github.io/simpcomp",
README_URL := Concatenation( ~.PackageWWWHome, "README" ),
```
This produces the invalid README_URL `https://simpcomp-team.github.io/simpcompREADME`. The `PackageInfoURL` is also broken. Add the missing slash to `PackageWWWHome` in `PackageInfo.g`, then copy the fixed `PackageInfo.g` to gh-pages and re-run `update.g` there, and it should work.

BTW, could you please reopen issues #10 and #8? Thanks

**Comment by simpcomp-team** [comment]
Sorry, I am slowly getting there. Just discovered that there was some old stuff in `package.yml` (although I though I ran `gap update.g` several times). Anyway, now everything works except: 

What is the right way to tell `GitHubPagesForGAP` to use `README.md` instead of `README`? I can manually change this in `package.yml` or refer to `README.md` in `PackageInfo.g`, but neither option seems right to me.

Issues #10 and #8 are already re-opened...

**Comment by fingolfin** [comment]
Nothing to be sorry about :-).

As to old stuff in `package.yml`: That file is recreated from scratch from `PackageInfo.g`. If it contains old stuff, then so does the `PackageInfo.g` file. Beware that you have two PackageInfo.g files now: one in the `master` branch, and one in `gh-pages`. A typical mistake is to edit one but then forget to update the other (once everything is working, ReleaseTools would that automatically for you, though).

The right way to rename README to README.md is to rename the file, and update the `README_URL` in `PackageInfo.g`; of course this needs to be done in both branches. Then re-run `update.g`. It extracts the name of the README to use from the README_URL.

I am not sure why referring to README.md in PackageInfo.g does not seem right to you, though? It should refer to the URL of the README file, and if that file is named `README.md`, then of course the README_URL should refer to it. 

Issues #8 and #10 are still shown as closed over here (and have been for the past 22 hours). I just reloaded them to double check.

**Comment by alex-konovalov** [comment]
Just to say, that now package update fails with this message:
```
Package: simpcomp
  changed components: [ "Persons", "PackageWWWHome", "README_URL", 
  "PackageInfoURL" ]
  ERROR (simpcomp): There are changed components in the new info file from
  http://raw.githubusercontent.com/simpcomp-team/simpcomp/master/web/PackageIn\
fo.g
   but .Version remains the same. This is not allowed, so the info file will n\
ot be changed
  PackageInfo.g is not accepted because of an error.
```
and I am happy for it to fail as long as the new package is not yet published. To run this transition smoothly, when you will publish new archive on a new package webpage, do not make further changes in PackageInfo.g until I will pick it up and point the system to the new URL.

Alternatively, I can just now tell the system to check the URL http://simpcomp-team.github.io/simpcomp/PackageInfo.g, if that's easier.

**Comment by simpcomp-team** [comment]
Ok, now they should be open.

Ok, if README.md is an acceptable name for README I have no complaints. I'll keep a copy in the repository in case someone is just guessing the standard name.

**Comment by alex-konovalov** [comment]
Check for updates went to a link which has a 404 error: 
```
Package: simpcomp
# Error (/circa/home/gap-jenkins/pkgadmin/pkgcache/simpcomp/tmp/tmpinfo.g): no\
 package info bound!
  WARNING (simpcomp): no success in download of the current info file 
  from http://raw.githubusercontent.com/simpcomp-team/simpcomp/master/web/PackageInfo.g
```
I've just enforced the new URL in https://github.com/gap-system/gap-distribution/commit/8a03e33a1f666c05bac41d1d2e428dd0b97b60f8 
so it will use the version from the website. Whatever happens, you may now commit changes to PackageInfo.g in the repository when you need.

**Comment by alex-konovalov** [comment]
This is now rectified. Check looks at the proper simpcomp page, sees the version already seen, and refuses to pick it up. As soon as the new release will be on the page, it will be picked up during the next scheduled run (workday mornings), of if I trigger it manually.

**Comment by simpcomp-team** [comment]
Ok, thanks a lot for all our help so far. Still preparing the release, it's taking a little longer than expected. 
I'll aim for the Monday morning run then.

**Comment by fingolfin** [comment]
Thanks! BTW, you could now set https://simpcomp-team.github.io/simpcomp/ on https://github.com/simpcomp-team/simpcomp as the homepage of this project: There should be an "Edit" button to the right of the headline text "A GAP package for working with simplicial complexes"; if you click on that, you can not only edit the description, but also set a homepage URL.

**Comment by simpcomp-team** [comment]
Added package homepage

**Comment by alex-konovalov** [comment]
Picked up new version! Thanks, this may be closed now.
```
* simpcomp - new version 2.1.9 discovered!!!
  ============================================
  Getting new archives from 
  http://github.com/simpcomp-team/simpcomp/releases/download/v2.1.9/simpcomp-2\
.1.9[ ".tar.gz" ]
  unpacking simpcomp-2.1.9.tar.gz
  Validation of the info file successful!
  Package simpcomp 2.1.9 from 20/10/2018 has dependencies:
  * NeededOtherPackages [ [ "GAPDoc", ">=0.9999" ], [ "io", ">=3.0" ] ]
  * GAP >=4.5
  * SuggestedOtherPackages [ [ "Homology", ">=1.4.4" ], [ "GRAPE", ">=4.4" ], 
  [ "Gauss", ">=2011.08.22" ], [ "MatricesForHomalg", ">=2011.10.08" ], 
  [ "homalg", ">=2011.10.05" ], [ "GaussForHomalg", ">=2011.08.10" ], 
  [ "Modules", ">=2011.10.05" ] ]
  finding text files  . . .

=====================text files==========================
simpcomp/COPYING
simpcomp/GPL
simpcomp/PackageInfo.g
simpcomp/README
simpcomp/README.md
simpcomp/init.g
simpcomp/read.g
simpcomp/doc/biblio.bib
simpcomp/doc/chap0.html
simpcomp/doc/chap0.txt
simpcomp/doc/chap1.html
simpcomp/doc/chap1.txt
simpcomp/doc/chap10.html
simpcomp/doc/chap10.txt
simpcomp/doc/chap11.html
simpcomp/doc/chap11.txt
simpcomp/doc/chap12.html
simpcomp/doc/chap12.txt
simpcomp/doc/chap13.html
simpcomp/doc/chap13.txt
simpcomp/doc/chap14.html
simpcomp/doc/chap14.txt
simpcomp/doc/chap15.html
simpcomp/doc/chap15.txt
simpcomp/doc/chap16.html
simpcomp/doc/chap16.txt
simpcomp/doc/chap17.html
simpcomp/doc/chap17.txt
simpcomp/doc/chap18.html
simpcomp/doc/chap18.txt
simpcomp/doc/chap2.html
simpcomp/doc/chap2.txt
simpcomp/doc/chap3.html
simpcomp/doc/chap3.txt
simpcomp/doc/chap4.html
simpcomp/doc/chap4.txt
simpcomp/doc/chap5.html
simpcomp/doc/chap5.txt
simpcomp/doc/chap6.html
simpcomp/doc/chap6.txt
simpcomp/doc/chap7.html
simpcomp/doc/chap7.txt
simpcomp/doc/chap8.html
simpcomp/doc/chap8.txt
simpcomp/doc/chap9.html
simpcomp/doc/chap9.txt
simpcomp/doc/chapBib.html
simpcomp/doc/chapBib.txt
simpcomp/doc/chapInd.html
simpcomp/doc/chapInd.txt
simpcomp/doc/demo.xml
simpcomp/doc/functions.xml
simpcomp/doc/howto.xml
simpcomp/doc/internals.xml
simpcomp/doc/morse.xml
simpcomp/doc/simpcomp.tex
simpcomp/doc/simpcomp.xml
simpcomp/doc/theory.xml
simpcomp/doc/titlepage.xml
simpcomp/lib/DMT.gd
simpcomp/lib/DMT.gi
simpcomp/lib/bistellar.gd
simpcomp/lib/bistellar.gi
simpcomp/lib/blowups.gd
simpcomp/lib/blowups.gi
simpcomp/lib/class3mflds.gd
simpcomp/lib/class3mflds.gi
simpcomp/lib/complex.gd
simpcomp/lib/complex.gi
simpcomp/lib/fromgroup.gd
simpcomp/lib/fromgroup.gi
simpcomp/lib/generate.gd
simpcomp/lib/generate.gi
simpcomp/lib/glprops.gd
simpcomp/lib/glprops.gi
simpcomp/lib/highlySymmetricSurfaces.gd
simpcomp/lib/highlySymmetricSurfaces.gi
simpcomp/lib/homology.gd
simpcomp/lib/homology.gi
simpcomp/lib/io.gd
simpcomp/lib/io.gi
simpcomp/lib/isosig.gd
simpcomp/lib/isosig.gi
simpcomp/lib/labelops.gd
simpcomp/lib/labelops.gi
simpcomp/lib/lib.gd
simpcomp/lib/lib.gi
simpcomp/lib/morse.gd
simpcomp/lib/morse.gi
simpcomp/lib/normalsurface.gd
simpcomp/lib/normalsurface.gi
simpcomp/lib/operations.gd
simpcomp/lib/operations.gi
simpcomp/lib/pkggrape.gi
simpcomp/lib/pkghom.gd
simpcomp/lib/pkghom.gi
simpcomp/lib/pkghomalg.gd
simpcomp/lib/pkghomalg.gi
simpcomp/lib/pkgnogrape.gi
simpcomp/lib/pkgnohom.gi
simpcomp/lib/prophandler.gd
simpcomp/lib/prophandler.gi
simpcomp/lib/propobject.gd
simpcomp/lib/propobject.gi
simpcomp/lib/tools.gd
simpcomp/lib/tools.gi
simpcomp/src/bistellar_move.cpp
simpcomp/src/bistellar_move.h
simpcomp/src/face.cpp
simpcomp/src/face.h
simpcomp/src/main.cpp
simpcomp/src/movable_complex.cpp
simpcomp/src/movable_complex.h
simpcomp/src/randomize_complex.cpp
simpcomp/src/randomize_complex.h
simpcomp/src/reduce_complex.cpp
simpcomp/src/reduce_complex.h
simpcomp/src/types.cpp
simpcomp/src/types.h
simpcomp/src/util.cpp
simpcomp/src/util.h
simpcomp/tst/gentest.gap
simpcomp/tst/simpcomp.tst

=====================end of the list of text files=======
=====================binary files========================
simpcomp/AUTHORS
simpcomp/CHANGELOG
simpcomp/Makefile.am
simpcomp/autogen.sh
simpcomp/configure.ac
simpcomp/version
simpcomp/complexes/complexes.idxb
simpcomp/complexes/manifolds/2Manifolds/MoebStrip.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG02.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG03.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG04.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG05.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG06.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG07.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG08.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG09.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG10.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG11.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG12.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG13.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG14.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG15.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG16.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG17.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG18.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG19.scb
simpcomp/complexes/manifolds/2Manifolds/SurfOG20.scb
...
```

**Comment by fingolfin** [comment]
This is indeed resolved.
