### ISSUE TITLE
Why is there both a GPL file and COPYING file?

### ISSUE THREAD

**Issue by fingolfin** [simpcomp-team/simpcomp#17]
The `COPYING` file contains both GPL 2 and GPL 3, concatenated. The `GPL` file only contains the GPL 2, and in a slightly older version (it still refers to the `L` in `LGPL` as "Library", not "Lesser").

Perhaps the file `GPL` is redundant? And I am not quite sure why the GPL3 is concatenated to the end of `COPYING`?

On the other hand, the  manual refers to the GFDL, which is however *not* included in the repository.

**Comment by simpcomp-team** [comment]
`GPL` is gone and `COPYING` now only contains GPL2.

**Comment by simpcomp-team** [comment]
Merging this into #14.
