### ISSUE TITLE
Implement support for ReleaseTools

### ISSUE THREAD

**Issue by simpcomp-team** [simpcomp-team/simpcomp#19]
Long term goal for simpcomp is to merge existing local release scripts with ReleaseTools.

**Comment by simpcomp-team** [comment]
Ok, so, I've been looking into implementing release tools. I think most major road blocks are out of the way (in particular, there won't be any `%%%` anymore in the github repository, ;))...

But I do have a question: the pdf manual is supposed to be in the repository, right? But every time I run AutoDoc(), the new pdf file is not identical with the old one - so re-running AutoDoc causes `verify_git_clean` on Line 266 of the release script to fail. Any suggestions?

**Comment by alex-konovalov** [comment]
@simpcomp-team the PDF manual is a derived file and it's not supposed to be in the repository.

Look at the Example GAP package as an example - it uses ReleaseTools and GitHubPagesForGAP: https://github.com/gap-packages/example

**Comment by simpcomp-team** [comment]
I will merge this to #27, since once #27 is resolved release tools are fully integrated into simpcomp.
