### ISSUE TITLE
Simpcomp tests fail in GAP master branch

### ISSUE THREAD

**Issue by alex-konovalov** [simpcomp-team/simpcomp#21]
As you can see it passed three days ago: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/571642135 but now fails: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/572585609, for the same version 2.1.10:

```
########> Diff in /home/gap/inst/gap-master/pkg/simpcomp/tst/simpcomp.tst:347

# Input is:

SCInterior(c);

# Expected output:

[SimplicialComplex

 Properties known: Dim, FacetsEx, IsEmpty, Name, Vertices.

 Name="Int(Bd(\beta^4))"

 Dim=2

/SimplicialComplex]

# But found:

[SimplicialComplex

 Properties known: Dim, FacetsEx, Name, Vertices.

 Name="Int(Bd(\beta^4))"

 Dim=2

/SimplicialComplex]

########

########> Diff in /home/gap/inst/gap-master/pkg/simpcomp/tst/simpcomp.tst:377

# Input is:

SCIsInKd(c,1);

# Expected output:

false

# But found:

Error, Variable: 'l' must have an assigned value

########

########> Diff in /home/gap/inst/gap-master/pkg/simpcomp/tst/simpcomp.tst:383

# Input is:

SCIsKStackedSphere(c,1);

# Expected output:

[ false, [SimplicialComplex

    

     Properties known: Dim, FacetsEx, Name, Vertices.

    

     Name="empty complex"

     Dim=-1

    

    /SimplicialComplex] ]

# But found:

Error, Variable: 'l' must have an assigned value

########

########> Diff in /home/gap/inst/gap-master/pkg/simpcomp/tst/simpcomp.tst:538

# Input is:

SCSpanningTree(c);

# Expected output:

[SimplicialComplex

 Properties known: Dim, FacetsEx, Name, Vertices.

 Name="spanning tree of Bd(\beta^4)"

 Dim=1

/SimplicialComplex]

# But found:

[SimplicialComplex

 Properties known: Dim, FacetsEx, Name, Vertices.

 Name="spanning tree of test"

 Dim=1

/SimplicialComplex]

########
```

**Comment by alex-konovalov** [comment]
1) is caused by missing `IsEmpty` - some change in the core system must have triggered that. Could it be https://github.com/gap-system/gap/pull/3592 by @stevelinton? (which might point out to a problem in simpcomp).

2,3) Could be undeclared local variable `l` hiding somewhere in your code?

4) Most likely a side effect of 2 and/or 3.

**Comment by alex-konovalov** [comment]
Out of interest, are there any particular reasons for a very verbose output

```
[SimplicialComplex

 Properties known: Dim, FacetsEx, Name, Vertices.

 Name="Int(Bd(\beta^4))"

 Dim=2

/SimplicialComplex]
```
and not, for example,

    <simplicial complex Int(Bd(\beta^4)) | dim=2>

**Comment by simpcomp-team** [comment]
I will look into it.

The reason for the verbose output is that one can see known properties right away. This would not work in a single line so we made several lines... 

Of course it is debatable whether this is really necessary. I agree that at least "Dim" and "Name" could go into the same line and line breaks could be removed.

**Comment by simpcomp-team** [comment]
Those error messages have now changed. I will make sure 2.1.13 will remove the remaining ones.

Let me think a little more about output format of simplicial complexes.

**Comment by alex-konovalov** [comment]
Would be most useful to work on #23 to run tests in this repository using GitHub actions, check their status and complete cleanup...

**Comment by fingolfin** [comment]
I think this is resolved now.
