### ISSUE TITLE
Setup continuous integration (e.g. using Travis CI)?

### ISSUE THREAD

**Issue by fingolfin** [simpcomp-team/simpcomp#23]
You could probably base this on what we do for other GAP packages; see <https://github.com/gap-system/pkg-ci-scripts>.

For examples in active use, you can basically look at any package in https://github.com/gap-packages/, e.g. https://github.com/gap-packages/cvec (which also compiles some C code). Main relevant file is https://github.com/gap-packages/cvec/blob/master/.travis.yml .

There is at least one hitch with doing this in simpcomp (which also is a concern for issue #19), and that's the missing version and release date in `PackageInfo.g`, which are placeholders here. But one could probably work around this by adding suitable calls to `sed` into `.travis.yml` which substitute with placeholder values GAP accepts (e.g. `"dev"` for the version, and `"01/01/2020" for the date). Even better would be if the actual version and release date were in this repository (from my POV -- of course you may of course have differing requirements which make this undesirable or unfeasible).

**Comment by alex-konovalov** [comment]
In the meantime, we moved from Travis CI to GitHub actions - an example could be found e.g. in https://github.com/gap-packages/example

**Comment by simpcomp-team** [comment]
Just so I understand what needs to be done for setting up GH Actions: I add a workflow file (eg., "CI.yml") and copy paste the code from CI.yml from the example package.

Now, what do I need to change in "CI.yml"? Does this work out of the box for simpcomp?

**Comment by alex-konovalov** [comment]
It may work since you don't have dependencies that you need to build. 

The best way is to try to add CI.yml in a feature branch, and then push it to your fork, to see if tests pass or not.

**Comment by fingolfin** [comment]
This is basically done now (once PR #37 is merged for sure)
