### ISSUE TITLE
Wrong function name in the README

### ISSUE THREAD

**Issue by alex-konovalov** [simpcomp-team/simpcomp#24]
The README has
```
gap> SCLoadPackage("simpcomp");
```
where is should have `LoadPackage`, and that's confusing - I've noticed this in this [Stackexchange question](https://stackoverflow.com/questions/57221351/how-to-upload-and-import-gap-packages-on-cocalc).

**Comment by simpcomp-team** [comment]
Yes, you are correct. I pushed a corrected version a couple of minutes ago.

**Comment by alex-konovalov** [comment]
Closed by 1256184a1659bd28e88b77bc017778763ebe14b6.

@simpcomp-team any plans for the new release?
