### ISSUE TITLE
Ship complexes in compressed format?

### ISSUE THREAD

**Issue by fingolfin** [simpcomp-team/simpcomp#25]
Right now, simpcomp is the biggest package bundled with GAP, taking about ~250 MB of space, of which >90% are taken by the `complexes` directory.

Now, GAP supports reading `.gz` files transparently -- that is, if GAP code tries to read a file named `foo`, but no such file exists, but a file `foo.gz` exists, it'll read `foo.gz` and decompress it transparently to the GAP code. So some packages ship their data files compressed with `gzip` (I'd not store them like this in the source repository, of course; rather, the code which creates the release archives can take care of it -- for packages using ReleaseTools, this is easily done via `.release` script, see https://github.com/gap-packages/YangBaxter/blob/master/.release or https://github.com/gap-packages/tomlib/blob/master/.release

I don't know if this is an option for simpcomp, as you also have C++ code which reads data, and I kinda suspect it is that code which reads them, so all I wrote above is moot, unless you were willing to add in code for reading .gz files into your C++ code (while using zlib for doing that is not very hard, of course far more work then not having to adjust anything, as it would be for GAP code reading the data ;-) -- and you certainly have limited time). 

Anyway, I thought I should bring it up here anyway (after it was raised during the GAP Days last week), just in case it feasible after all!

**Comment by RussWoodroofe** [comment]
Second the suggestion!

**Comment by simpcomp-team** [comment]
Thank you for raising this issue.

Most of the content of the complexes directory (a library of simplicial complexes / triangulated manifolds) is actually content that, I believe, is rarely used / could be used as an external resource. So I have been thinking about outsourcing most of this content.

I am also in the process of making simpcomp more inline with the tools available for maintaining the package (see other issues about release tools, continuous integration, etc). 

Now, when I say "in the process" of doing this, I realise that all this takes me a very long time. I really hope that I will be able to get back to this soon (March, April) and I apologise for the glacial pace.

**Comment by fingolfin** [comment]
No worries about pace, I know how it is :-). If you have any questions about ReleaseTools or the other stuff, let me know, I'd be happy to help.

As to those files: in the atlasrep package, there is code to automatically download certain files from a server if the user tries to access them / requests them; perhaps something similar could (eventually!) be done for simpcomp? We've debated whether one could provide such a mechanism in a way that it is implemented once and then used by multiple packages (see https://github.com/gap-system/gap/issues/4285) but so far this is just talk.

**Comment by simpcomp-team** [comment]
This is now the next item on the agenda.

**Comment by simpcomp-team** [comment]
A smaller complex library will be part of 2.1.13.
