### ISSUE TITLE
Missing help files

### ISSUE THREAD

**Issue by RussWoodroofe** [simpcomp-team/simpcomp#26]
Simpcomp, at least as of the version shipped with GAP 4.11.0, is missing the manual.css and manual.js (and probably some other files) from its doc directory.

The help doesn't look so great without the css to style it.

**Comment by alex-konovalov** [comment]
@simpcomp-team aren't  you using https://github.com/gap-system/ReleaseTools - with them, these files are taken care of automatically.

**Comment by simpcomp-team** [comment]
I was implementing the use of ReleaseTools but I think there are still some I need attend to (generated files in the repository, etc.). I also wanted to reduce the size of my complex library.

I will look into it.

**Comment by simpcomp-team** [comment]
I properly released simpcomp using the release tools (2.1.11 was incomplete) and now manual.css and manual.js are in the doc folder.

**Comment by simpcomp-team** [comment]
I will close this one and link it to #27 because those two are related.
