### ISSUE TITLE
Outfile and IsoSig in SCFromGroupExt

### ISSUE THREAD

**Issue by nerdyjoe314** [simpcomp-team/simpcomp#28]
If you call SCFromGroupExt with the removeDoubleEntries flag on and an outfile specified, the results of the computation are not written to the outfile.

**Comment by simpcomp-team** [comment]
Thanks. :) Will look into it.

**Comment by fingolfin** [comment]
@simpcomp-team any news on this?

**Comment by simpcomp-team** [comment]
Just fixed this. It will be part of the next release.
