### ISSUE TITLE
Test failures in GAP 4.9 and 4.10

### ISSUE THREAD

**Issue by fingolfin** [simpcomp-team/simpcomp#39]
With 4.9 and 4.10, we get the following test failure. I can't judge whether it indicates an actual regression, is trivial, or something else:
```
########> Diff in tst/simpcomp.tst:377
# Input is:
SCSpanningTree(c);
# Expected output:
<SimplicialComplex: spanning tree of test | dim = 1 | n = 8>
# But found:
<SimplicialComplex: spanning tree of Bd(\beta^4) | dim = 1 | n = 8>
########
simpcomp package test
msecs: 10370
```

_Originally posted by @fingolfin in https://github.com/simpcomp-team/simpcomp/issues/37#issuecomment-1064564292_

**Comment by simpcomp-team** [comment]
I think I fixed these issues. But I am still struggling with the (correct) built manual.
