### ISSUE TITLE
Make a new release to ensure compatibility with GAP 4.9

### ISSUE THREAD

**Issue by fingolfin** [simpcomp-team/simpcomp#5]
In a06ed1859571dac5c31a22ba7031b9935f875c2e you made a change to adapt to the new `Union` code in the GAP master branch.

However, as far as I can tell, this change is not yet in any simpcomp release. It would be great if you could make a release, so that when GAP 4.9 is released (hopefully later this year), your package works out of the box.

Thanks!

**Comment by simpcomp-team** [comment]
Just created a new release. Hope this fixes the issue.

**Comment by alex-konovalov** [comment]
Seems so - I think this may now be closed.
