### ISSUE TITLE
Diffs in tests with GAP 4.9.1 release candidate

### ISSUE THREAD

**Issue by alex-konovalov** [simpcomp-team/simpcomp#6]
There are currently some diffs in the package tests when they are run with the `stable-4.9` branch of the GAP repository. Please see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging to inspect them: click on the line corresponding to this package and scroll till the very end of the log file to see the output of the package tests, the summary, and further instructions.

As soon as the package tests will run without diffs, they will be moved to https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9. This will be very helpful to monitor in the future that the package is still usable and that no changes in the GAP system break the package.

**Comment by simpcomp-team** [comment]
Hi Alex,

Looks like this is due to a tweak in the output of "StructureDescription". Uploaded a new version 2.1.8. Let's hope this will take care of it.

**Comment by alex-konovalov** [comment]
Thanks @simpcomp-team - new version is picked up, testing is underway.

**Comment by alex-konovalov** [comment]
Happy to tell you - tests now pass: https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging/jobs/339716446 

I will move your package from staging to release-ready set of tests shortly. Thanks!
