### ISSUE TITLE
bistellar executable is not put into correct location

### ISSUE THREAD

**Issue by fingolfin** [simpcomp-team/simpcomp#9]
Even after fixing issue #8, it seems (though I have not actually verified) that one cannot use the `bistellar` executable via `simpcomp` from GAP, because the GAP code to load it does this (which is indeed the "right" way to go about it):
```gap
  dir := DirectoriesPackageLibrary("simpcomp", "bin");
  ...
  bin := Filename(dir, "bistellar");
  ...
  stream := InputOutputLocalProcess(DirectoryCurrent(), bin, []);
```
But this requires `bistellar` to be in `simpcomp/bin/$GAPARCH/` or at least in `simpcomp/bin`, but the build system does not attempt to actually place it there.

**Comment by simpcomp-team** [comment]
See [#8](https://github.com/simpcomp-team/simpcomp/issues/8).

**Comment by fingolfin** [comment]
Resolve by 55f207ee3b8bacb12122c63b8d525b745bd98386 resp. PR #13
